# Servidor
server.port=${SERVER_PORT:8081}

# Pool de conexoes
spring.datasource.hikari.pool-name=ImoblyHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Logs
logging.level.root=INFO
logging.level.com.mscosta.imoblygestapi=DEBUG
logging.level.org.flywaydb=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
