spring.application.name=imobly-gest-api
# Servidor
server.port=8081
# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/misuradb
spring.datasource.username=${DB_USERNAME:mscosta}
spring.datasource.password=${DB_PASSWORD:mscosta}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=ImoblyHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Logs
logging.level.root=INFO
logging.level.com.mscosta.imoblygestapi=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
