spring.datasource.url=${DB_URL:jdbc:postgresql://dbmscosta.cpe8qe8qktfq.sa-east-1.rds.amazonaws.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:mscosta}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.pool-name=ImoblyHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

logging.level.root=INFO
logging.level.com.mscosta.imoblygestapi=INFO
