spring.application.name=ct-aluguel-api

#configuracoes de banco
spring.datasource.url=jdbc:postgresql://localhost:5432/ct-aluguel-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.hibernate.ddl-auto=update

# Nivel de log global
logging.level.root=INFO

# Nivel de log especifico para seus pacotes
logging.level.com.mscosta.ctaluguelapi=DEBUG

# Formatacao do log (opcional)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
